[profile.default]
solc = "0.8.24"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 1
libs = ["../../node_modules"]
src = "src"
test = "test"
out = "out"
extra_output_files = ["abi", "evm.bytecode"]
fs_permissions = [{ access = "read", path = "./" }]

[profile.garnet]
eth_rpc_url = "https://17069.rpc.thirdweb.com/27ba31e8fedf04a29c6004f4f745038e"

[profile.redstone]
eth_rpc_url = "https://rpc.redstonechain.com/"
